name: Guestbook
on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  update_guestbook:
    name: Update Guestbook
    if: ${{ github.event.issue.title == 'Guestbook' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Update Guestbook
        uses: actions/github-script@v6
        with:
          script: |
            const query = `query($owner:String!, $name:String!, $issue_number:Int!) {
              repository(owner:$owner, name:$name){
                issue(number:$issue_number) {
                  comments(first:100, orderBy:{direction:DESC, field:UPDATED_AT}) {
                    nodes {
                      author {
                        avatarUrl(size: 24)
                        login
                        url
                      }
                      bodyText
                      updatedAt
                    }
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              issue_number: context.issue.number
            };
            const result = await github.graphql(query, variables);
            
            const date = new Intl.DateTimeFormat('en-US', {
                dateStyle: 'short'
              }).format(new Date(comment.updatedAt));
            const guestbookTable = result.repository.issue.comments.nodes.reduce((table, comment) => {
              const roundedAvatarUrl = `https://images.weserv.nl/?url=${encodeURIComponent(comment.author.avatarUrl)}&h=24&w=24&fit=cover&mask=circle&maxage=7d`;
              const authorInfo = `<a href="${comment.author.url}"><img width="24" height="24" src="${roundedAvatarUrl}" alt="${comment.author.login}"> ${comment.author.login}</a>`;
              const formattedDate = new Intl.DateTimeFormat('en-US', {
                dateStyle: 'short'
              }).format(new Date(comment.updatedAt));
            
             return `${table}| ${authorInfo} | ${formattedDate} | ${comment.bodyText} |\n`;
            }, "| Author | Date | Message |\n|---|---|---|\n");
            const fs = require('fs');
            const readme = fs.readFileSync('README.md', 'utf8');
            const updatedReadme = readme.replace(
              /(?<=<!-- Guestbook -->\n)[\S\s]*?(?=\n<!-- \/Guestbook -->)/,
              guestbookTable
            );
            fs.writeFileSync('README.md', updatedReadme, 'utf8');

      - name: Add guestbook update
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am 'chore: update guestbook'
          git push
